
FROM python:3.9-slim


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /src


COPY requirements-fastapi.txt /src/


RUN pip install --no-cache-dir -r requirements-fastapi.txt


COPY ./src /src/


CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
